CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE t_e_catparticipant_cppt (
    cppt_id integer GENERATED BY DEFAULT AS IDENTITY,
    cppt_nom character varying(255) NOT NULL,
    CONSTRAINT "PK_t_e_catparticipant_cppt" PRIMARY KEY (cppt_id)
);

CREATE TABLE t_e_cb_cb (
    cb_idcb integer GENERATED BY DEFAULT AS IDENTITY,
    cb_cvc character varying(255) NOT NULL,
    cb_code character varying(255) NOT NULL,
    cb_anneeexp character varying(255) NOT NULL,
    cb_moisexp character varying(255) NOT NULL,
    CONSTRAINT "PK_t_e_cb_cb" PRIMARY KEY (cb_idcb)
);

CREATE TABLE t_e_destination_dst (
    dst_id integer GENERATED BY DEFAULT AS IDENTITY,
    dst_libelle character varying(255) NOT NULL,
    dst_description text NOT NULL,
    CONSTRAINT "PK_t_e_destination_dst" PRIMARY KEY (dst_id)
);

CREATE TABLE t_e_etoilehotel_eth (
    eth_nb integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_t_e_etoilehotel_eth" PRIMARY KEY (eth_nb)
);

CREATE TABLE t_e_image_img (
    img_id integer GENERATED BY DEFAULT AS IDENTITY,
    img_libelle character varying(255) NOT NULL,
    CONSTRAINT "PK_t_e_image_img" PRIMARY KEY (img_id)
);

CREATE TABLE t_e_partenaire_prt (
    prt_id integer GENERATED BY DEFAULT AS IDENTITY,
    prt_nom character varying(255) NOT NULL,
    prt_rue character varying(255) NOT NULL,
    prt_cp character varying(5) NOT NULL,
    prt_ville character varying(255) NOT NULL,
    prt_photo character varying(255) NOT NULL,
    prt_email character varying(255) NOT NULL,
    prt_contact character varying(10) NOT NULL,
    prt_detailpartenaire text NOT NULL,
    CONSTRAINT "PK_t_e_partenaire_prt" PRIMARY KEY (prt_id)
);

CREATE TABLE t_e_theme_thm (
    thm_id integer GENERATED BY DEFAULT AS IDENTITY,
    thm_libelle character varying(250) NOT NULL,
    thm_imgthemepage character varying(255) NOT NULL,
    thm_contenuthemepage text NOT NULL,
    CONSTRAINT "PK_t_e_theme_thm" PRIMARY KEY (thm_id)
);

CREATE TABLE t_e_typeactivite_tac (
    tac_id integer GENERATED BY DEFAULT AS IDENTITY,
    tac_libelletype character varying(250) NOT NULL,
    CONSTRAINT "PK_t_e_typeactivite_tac" PRIMARY KEY (tac_id)
);

CREATE TABLE t_e_typevisite_tvs (
    tvs_id integer GENERATED BY DEFAULT AS IDENTITY,
    tvs_libelle character varying(250) NOT NULL,
    CONSTRAINT "PK_t_e_typevisite_tvs" PRIMARY KEY (tvs_id)
);

CREATE TABLE t_e_client_clt (
    avi_idavis integer NOT NULL,
    cb_idcb integer NOT NULL,
    clt_id integer GENERATED BY DEFAULT AS IDENTITY,
    clt_nom character varying(255) NOT NULL,
    clt_prenom character varying(255) NOT NULL,
    clt_datenaissance date NOT NULL,
    clt_sexe text NOT NULL,
    clt_motdepasse character varying(255) NOT NULL,
    clt_email character varying(255) NOT NULL,
    "CbClientNavigationIdCb" integer NOT NULL,
    CONSTRAINT "PK_t_e_client_clt" PRIMARY KEY (clt_id),
    CONSTRAINT "FK_t_e_client_clt_t_e_cb_cb_CbClientNavigationIdCb" FOREIGN KEY ("CbClientNavigationIdCb") REFERENCES t_e_cb_cb (cb_idcb) ON DELETE CASCADE
);

CREATE TABLE t_h_cave_cav (
    prt_id integer NOT NULL,
    "PartenaireCaveNavigationIdPartenaire" integer NOT NULL,
    CONSTRAINT "PK_t_h_cave_cav" PRIMARY KEY (prt_id),
    CONSTRAINT "FK_t_h_cave_cav_t_e_partenaire_prt_PartenaireCaveNavigationIdP~" FOREIGN KEY ("PartenaireCaveNavigationIdPartenaire") REFERENCES t_e_partenaire_prt (prt_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_h_cave_cav_t_e_partenaire_prt_prt_id" FOREIGN KEY (prt_id) REFERENCES t_e_partenaire_prt (prt_id) ON DELETE CASCADE
);

CREATE TABLE t_h_hotel_htl (
    ect_nb integer NOT NULL,
    prt_id integer NOT NULL,
    "PartenaireHotelNavigationIdPartenaire" integer NOT NULL,
    "EtoileHotelHotelNavigationNbEtoileHotel" integer NOT NULL,
    CONSTRAINT "PK_t_h_hotel_htl" PRIMARY KEY (prt_id),
    CONSTRAINT "FK_t_h_hotel_htl_t_e_etoilehotel_eth_EtoileHotelHotelNavigatio~" FOREIGN KEY ("EtoileHotelHotelNavigationNbEtoileHotel") REFERENCES t_e_etoilehotel_eth (eth_nb) ON DELETE CASCADE,
    CONSTRAINT "FK_t_h_hotel_htl_t_e_partenaire_prt_PartenaireHotelNavigationI~" FOREIGN KEY ("PartenaireHotelNavigationIdPartenaire") REFERENCES t_e_partenaire_prt (prt_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_h_hotel_htl_t_e_partenaire_prt_prt_id" FOREIGN KEY (prt_id) REFERENCES t_e_partenaire_prt (prt_id) ON DELETE CASCADE
);

CREATE TABLE t_e_sejour_sjr (
    thm_id integer NOT NULL,
    dst_id integer NOT NULL,
    sjr_id integer GENERATED BY DEFAULT AS IDENTITY,
    sjr_titre character varying(255) NOT NULL,
    sjr_photo character varying(255) NOT NULL,
    sjr_prix numeric NOT NULL,
    sjr_description text NOT NULL,
    sjr_nbjour integer NOT NULL,
    sjr_nbnuit integer NOT NULL,
    sjr_libelletemps character varying(255) NOT NULL,
    sjr_notemoyenne numeric NOT NULL,
    "DestinationSejourNavigationIdDestination" integer NOT NULL,
    "ThemeSejourNavigationIdTheme" integer NOT NULL,
    CONSTRAINT "PK_t_e_sejour_sjr" PRIMARY KEY (sjr_id),
    CONSTRAINT "FK_t_e_sejour_sjr_t_e_destination_dst_DestinationSejourNavigat~" FOREIGN KEY ("DestinationSejourNavigationIdDestination") REFERENCES t_e_destination_dst (dst_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_e_sejour_sjr_t_e_theme_thm_ThemeSejourNavigationIdTheme" FOREIGN KEY ("ThemeSejourNavigationIdTheme") REFERENCES t_e_theme_thm (thm_id) ON DELETE CASCADE
);

CREATE TABLE t_h_societe_sct (
    act_id integer NOT NULL,
    prt_id integer NOT NULL,
    "TypeActiviteSocieteNavigationIdTypeActivite" integer NOT NULL,
    CONSTRAINT "PK_t_h_societe_sct" PRIMARY KEY (prt_id),
    CONSTRAINT "FK_t_h_societe_sct_t_e_partenaire_prt_prt_id" FOREIGN KEY (prt_id) REFERENCES t_e_partenaire_prt (prt_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_h_societe_sct_t_e_typeactivite_tac_TypeActiviteSocieteNav~" FOREIGN KEY ("TypeActiviteSocieteNavigationIdTypeActivite") REFERENCES t_e_typeactivite_tac (tac_id) ON DELETE CASCADE
);

CREATE TABLE t_e_adresse_adr (
    adr_id integer GENERATED BY DEFAULT AS IDENTITY,
    clt_idclient integer NOT NULL,
    adr_libelle character varying(250) NOT NULL,
    adr_rueadresse character varying(250) NOT NULL,
    adr_ville character varying(250) NOT NULL,
    adr_cp text NOT NULL,
    adr_pays character varying(255) NOT NULL,
    "ClientAdresseNavigationIdClient" integer NOT NULL,
    CONSTRAINT "PK_t_e_adresse_adr" PRIMARY KEY (adr_id),
    CONSTRAINT "FK_t_e_adresse_adr_t_e_client_clt_ClientAdresseNavigationIdCli~" FOREIGN KEY ("ClientAdresseNavigationIdClient") REFERENCES t_e_client_clt (clt_id) ON DELETE CASCADE
);

CREATE TABLE t_e_paiement_pmt (
    pmt_idpmt integer GENERATED BY DEFAULT AS IDENTITY,
    clt_idclient integer NOT NULL,
    pmt_libelle character varying(255) NOT NULL,
    pmt_preference boolean NOT NULL,
    "ClientPaiementNavigationIdClient" integer NOT NULL,
    CONSTRAINT "PK_t_e_paiement_pmt" PRIMARY KEY (pmt_idpmt),
    CONSTRAINT "FK_t_e_paiement_pmt_t_e_client_clt_ClientPaiementNavigationIdC~" FOREIGN KEY ("ClientPaiementNavigationIdClient") REFERENCES t_e_client_clt (clt_id) ON DELETE CASCADE
);

CREATE TABLE t_e_visite_vst (
    tvs_id integer NOT NULL,
    cav_id integer NOT NULL,
    vst_id integer GENERATED BY DEFAULT AS IDENTITY,
    vst_libelle character varying(255) NOT NULL,
    vst_description text NOT NULL,
    vst_horaire time without time zone NOT NULL,
    "TypeVisiteVisiteNavigationIdTypeVisite" integer NOT NULL,
    "CaveVisiteNavigationIdPartenaire" integer NOT NULL,
    CONSTRAINT "PK_t_e_visite_vst" PRIMARY KEY (vst_id),
    CONSTRAINT "FK_t_e_visite_vst_t_e_typevisite_tvs_TypeVisiteVisiteNavigatio~" FOREIGN KEY ("TypeVisiteVisiteNavigationIdTypeVisite") REFERENCES t_e_typevisite_tvs (tvs_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_e_visite_vst_t_h_cave_cav_CaveVisiteNavigationIdPartenaire" FOREIGN KEY ("CaveVisiteNavigationIdPartenaire") REFERENCES t_h_cave_cav (prt_id) ON DELETE CASCADE
);

CREATE TABLE t_e_hebergement_hbg (
    hbg_id integer GENERATED BY DEFAULT AS IDENTITY,
    prt_id integer NOT NULL,
    hbg_libelle character varying(255) NOT NULL,
    hbg_description text NOT NULL,
    hbg_nbchambre integer NOT NULL,
    hbg_horaire time without time zone NOT NULL,
    "HotelHebergementNavigationIdPartenaire" integer NOT NULL,
    CONSTRAINT "PK_t_e_hebergement_hbg" PRIMARY KEY (hbg_id),
    CONSTRAINT "FK_t_e_hebergement_hbg_t_h_hotel_htl_HotelHebergementNavigatio~" FOREIGN KEY ("HotelHebergementNavigationIdPartenaire") REFERENCES t_h_hotel_htl (prt_id) ON DELETE CASCADE
);

CREATE TABLE t_e_avis_avi (
    clt_id integer NOT NULL,
    sjr_id integer NOT NULL,
    avi_id integer GENERATED BY DEFAULT AS IDENTITY,
    avi_note integer NOT NULL,
    avi_commentaire text NOT NULL,
    avi_titreavis character varying(255) NOT NULL,
    avi_dateavis date NOT NULL,
    avi_avissignale boolean NOT NULL,
    avi_typesignalement character varying(255) NOT NULL,
    "ClientAvisNavigationIdClient" integer NOT NULL,
    "SejourAvisNavigationIdSejour" integer NOT NULL,
    CONSTRAINT "PK_t_e_avis_avi" PRIMARY KEY (avi_id),
    CONSTRAINT "FK_t_e_avis_avi_t_e_client_clt_ClientAvisNavigationIdClient" FOREIGN KEY ("ClientAvisNavigationIdClient") REFERENCES t_e_client_clt (clt_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_e_avis_avi_t_e_sejour_sjr_SejourAvisNavigationIdSejour" FOREIGN KEY ("SejourAvisNavigationIdSejour") REFERENCES t_e_sejour_sjr (sjr_id) ON DELETE CASCADE
);

CREATE TABLE t_j_participe_ppt (
    cpt_id integer GENERATED BY DEFAULT AS IDENTITY,
    sjr_id integer GENERATED BY DEFAULT AS IDENTITY,
    "CatParticipantParticipeNavigationIdCategorieParticipant" integer NOT NULL,
    "SejourParticipeNavigationIdSejour" integer NOT NULL,
    CONSTRAINT pk_participe PRIMARY KEY (cpt_id, sjr_id),
    CONSTRAINT "FK_t_j_participe_ppt_t_e_catparticipant_cppt_CatParticipantPar~" FOREIGN KEY ("CatParticipantParticipeNavigationIdCategorieParticipant") REFERENCES t_e_catparticipant_cppt (cppt_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_j_participe_ppt_t_e_sejour_sjr_SejourParticipeNavigationI~" FOREIGN KEY ("SejourParticipeNavigationIdSejour") REFERENCES t_e_sejour_sjr (sjr_id) ON DELETE CASCADE
);

CREATE TABLE "PartenaireSociete" (
    "PartenaireSocieteNavigationIdPartenaire" integer NOT NULL,
    "SocietePartenaireNavigationIdPartenaire" integer NOT NULL,
    CONSTRAINT "PK_PartenaireSociete" PRIMARY KEY ("PartenaireSocieteNavigationIdPartenaire", "SocietePartenaireNavigationIdPartenaire"),
    CONSTRAINT "FK_PartenaireSociete_t_e_partenaire_prt_PartenaireSocieteNavig~" FOREIGN KEY ("PartenaireSocieteNavigationIdPartenaire") REFERENCES t_e_partenaire_prt (prt_id) ON DELETE CASCADE,
    CONSTRAINT "FK_PartenaireSociete_t_h_societe_sct_SocietePartenaireNavigati~" FOREIGN KEY ("SocietePartenaireNavigationIdPartenaire") REFERENCES t_h_societe_sct (prt_id) ON DELETE CASCADE
);

CREATE TABLE t_e_activite_act (
    act_id integer GENERATED BY DEFAULT AS IDENTITY,
    prt_id integer NOT NULL,
    act_libelle character varying(255) NOT NULL,
    act_description text NOT NULL,
    act_ruerdv character varying(255) NOT NULL,
    act_cprdv character varying(5) NOT NULL,
    act_villerdv character varying(255) NOT NULL,
    act_horaire time without time zone NOT NULL,
    "SocieteActiviteNavigationIdPartenaire" integer NOT NULL,
    CONSTRAINT "PK_t_e_activite_act" PRIMARY KEY (act_id),
    CONSTRAINT "FK_t_e_activite_act_t_h_societe_sct_SocieteActiviteNavigationI~" FOREIGN KEY ("SocieteActiviteNavigationIdPartenaire") REFERENCES t_h_societe_sct (prt_id) ON DELETE CASCADE
);

CREATE TABLE t_e_commande_cmd (
    cmd_idclient integer NOT NULL,
    cmd_idpaiement integer NOT NULL,
    cmd_id integer GENERATED BY DEFAULT AS IDENTITY,
    cmd_datecommande date NOT NULL,
    cmd_prixcommande numeric NOT NULL,
    cmd_quantite integer NOT NULL,
    cmd_message text NOT NULL,
    cmd_cheminfacture text NOT NULL,
    cmd_estcheque boolean NOT NULL,
    "ClientCommandeNavigationIdClient" integer NOT NULL,
    "PaiementCommandeNavigationIdPaiement" integer NOT NULL,
    CONSTRAINT "PK_t_e_commande_cmd" PRIMARY KEY (cmd_id),
    CONSTRAINT ck_cmd_prix CHECK (cmd_quantite > 0),
    CONSTRAINT "FK_t_e_commande_cmd_t_e_client_clt_ClientCommandeNavigationIdC~" FOREIGN KEY ("ClientCommandeNavigationIdClient") REFERENCES t_e_client_clt (clt_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_e_commande_cmd_t_e_paiement_pmt_PaiementCommandeNavigatio~" FOREIGN KEY ("PaiementCommandeNavigationIdPaiement") REFERENCES t_e_paiement_pmt (pmt_idpmt) ON DELETE CASCADE
);

CREATE TABLE t_e_etape_etp (
    sjr_id integer NOT NULL,
    hbg_id integer NOT NULL,
    etp_id integer GENERATED BY DEFAULT AS IDENTITY,
    etp_titre character varying(255) NOT NULL,
    etp_description text NOT NULL,
    etp_photo text NOT NULL,
    etp_url character varying(255) NOT NULL,
    etp_video character varying(255) NOT NULL,
    "HebergementEtapeNavigationIdHebergement" integer NOT NULL,
    "SejourEtapeNavigationIdSejour" integer NOT NULL,
    CONSTRAINT "PK_t_e_etape_etp" PRIMARY KEY (etp_id),
    CONSTRAINT "FK_t_e_etape_etp_t_e_hebergement_hbg_HebergementEtapeNavigatio~" FOREIGN KEY ("HebergementEtapeNavigationIdHebergement") REFERENCES t_e_hebergement_hbg (hbg_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_e_etape_etp_t_e_sejour_sjr_SejourEtapeNavigationIdSejour" FOREIGN KEY ("SejourEtapeNavigationIdSejour") REFERENCES t_e_sejour_sjr (sjr_id) ON DELETE CASCADE
);

CREATE TABLE t_e_reponseavis_rav (
    rav_id integer GENERATED BY DEFAULT AS IDENTITY,
    rav_idavis integer NOT NULL,
    rav_commentaire text NOT NULL,
    CONSTRAINT pk_reponse_avis PRIMARY KEY (rav_id, rav_idavis),
    CONSTRAINT "FK_t_e_reponseavis_rav_t_e_avis_avi_rav_idavis" FOREIGN KEY (rav_idavis) REFERENCES t_e_avis_avi (avi_id) ON DELETE CASCADE
);

CREATE TABLE t_j_imageavis_ima (
    avi_id integer GENERATED BY DEFAULT AS IDENTITY,
    im_id integer GENERATED BY DEFAULT AS IDENTITY,
    "AvisImageAvisNavigationIdAvis" integer NOT NULL,
    "ImageImageAvisNavigationIdImage" integer NOT NULL,
    CONSTRAINT pk_image_avis PRIMARY KEY (im_id, avi_id),
    CONSTRAINT "FK_t_j_imageavis_ima_t_e_avis_avi_AvisImageAvisNavigationIdAvis" FOREIGN KEY ("AvisImageAvisNavigationIdAvis") REFERENCES t_e_avis_avi (avi_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_j_imageavis_ima_t_e_image_img_ImageImageAvisNavigationIdI~" FOREIGN KEY ("ImageImageAvisNavigationIdImage") REFERENCES t_e_image_img (img_id) ON DELETE CASCADE
);

CREATE TABLE t_e_boncommande_bcm (
    bcm_id integer GENERATED BY DEFAULT AS IDENTITY,
    cmd_id integer NOT NULL,
    bcm_codeboncommande character varying(255) NOT NULL,
    bcm_datevalidite date NOT NULL,
    bcm_estvalide boolean NOT NULL,
    "CommandeBonCommandeNavigationRefCommande" integer NOT NULL,
    CONSTRAINT "PK_t_e_boncommande_bcm" PRIMARY KEY (bcm_id),
    CONSTRAINT "FK_t_e_boncommande_bcm_t_e_commande_cmd_CommandeBonCommandeNav~" FOREIGN KEY ("CommandeBonCommandeNavigationRefCommande") REFERENCES t_e_commande_cmd (cmd_id) ON DELETE CASCADE
);

CREATE TABLE t_e_bonreduction_brd (
    brd_id integer GENERATED BY DEFAULT AS IDENTITY,
    cmd_id integer NOT NULL,
    brd_codebonreduction character varying(255) NOT NULL,
    brd_datevalidite date NOT NULL,
    brd_estvalide boolean NOT NULL,
    "CommandeBonReductionNavigationRefCommande" integer NOT NULL,
    CONSTRAINT "PK_t_e_bonreduction_brd" PRIMARY KEY (brd_id),
    CONSTRAINT "FK_t_e_bonreduction_brd_t_e_commande_cmd_CommandeBonReductionN~" FOREIGN KEY ("CommandeBonReductionNavigationRefCommande") REFERENCES t_e_commande_cmd (cmd_id) ON DELETE CASCADE
);

CREATE TABLE t_j_reservation_rsv (
    cmd_id integer GENERATED BY DEFAULT AS IDENTITY,
    sjr_id integer GENERATED BY DEFAULT AS IDENTITY,
    rsv_datedebutreservation date NOT NULL,
    rsv_estcadeau boolean NOT NULL,
    rsv_nbenfant integer NOT NULL,
    rsv_nbadulte integer NOT NULL,
    rsv_nbchambre integer NOT NULL,
    "CommandeReservationNavigationRefCommande" integer NOT NULL,
    "SejourReservationNavigationIdSejour" integer NOT NULL,
    CONSTRAINT pk_reservation PRIMARY KEY (sjr_id, cmd_id),
    CONSTRAINT "FK_t_j_reservation_rsv_t_e_commande_cmd_CommandeReservationNav~" FOREIGN KEY ("CommandeReservationNavigationRefCommande") REFERENCES t_e_commande_cmd (cmd_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_j_reservation_rsv_t_e_sejour_sjr_SejourReservationNavigat~" FOREIGN KEY ("SejourReservationNavigationIdSejour") REFERENCES t_e_sejour_sjr (sjr_id) ON DELETE CASCADE
);

CREATE TABLE t_j_effectue_efc (
    act_id integer GENERATED BY DEFAULT AS IDENTITY,
    etp_id integer GENERATED BY DEFAULT AS IDENTITY,
    "ActiviteEffectueNavigationIdActivite" integer NOT NULL,
    "EtapeEffectueNavigationIdEtape" integer NOT NULL,
    CONSTRAINT pk_effectue PRIMARY KEY (act_id, etp_id),
    CONSTRAINT "FK_t_j_effectue_efc_t_e_activite_act_ActiviteEffectueNavigatio~" FOREIGN KEY ("ActiviteEffectueNavigationIdActivite") REFERENCES t_e_activite_act (act_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_j_effectue_efc_t_e_etape_etp_EtapeEffectueNavigationIdEta~" FOREIGN KEY ("EtapeEffectueNavigationIdEtape") REFERENCES t_e_etape_etp (etp_id) ON DELETE CASCADE
);

CREATE TABLE t_j_faitpartiede_fpd (
    vst_id integer NOT NULL,
    etp_id integer NOT NULL,
    CONSTRAINT pk_fait_parti_de PRIMARY KEY (vst_id, etp_id),
    CONSTRAINT "FK_t_j_faitpartiede_fpd_t_e_etape_etp_etp_id" FOREIGN KEY (etp_id) REFERENCES t_e_etape_etp (etp_id) ON DELETE CASCADE,
    CONSTRAINT "FK_t_j_faitpartiede_fpd_t_e_visite_vst_vst_id" FOREIGN KEY (vst_id) REFERENCES t_e_visite_vst (vst_id) ON DELETE CASCADE
);

CREATE INDEX "IX_PartenaireSociete_SocietePartenaireNavigationIdPartenaire" ON "PartenaireSociete" ("SocietePartenaireNavigationIdPartenaire");

CREATE INDEX "IX_t_e_activite_act_SocieteActiviteNavigationIdPartenaire" ON t_e_activite_act ("SocieteActiviteNavigationIdPartenaire");

CREATE INDEX "IX_t_e_adresse_adr_ClientAdresseNavigationIdClient" ON t_e_adresse_adr ("ClientAdresseNavigationIdClient");

CREATE INDEX "IX_t_e_avis_avi_ClientAvisNavigationIdClient" ON t_e_avis_avi ("ClientAvisNavigationIdClient");

CREATE INDEX "IX_t_e_avis_avi_SejourAvisNavigationIdSejour" ON t_e_avis_avi ("SejourAvisNavigationIdSejour");

CREATE INDEX "IX_t_e_boncommande_bcm_CommandeBonCommandeNavigationRefCommande" ON t_e_boncommande_bcm ("CommandeBonCommandeNavigationRefCommande");

CREATE INDEX "IX_t_e_bonreduction_brd_CommandeBonReductionNavigationRefComma~" ON t_e_bonreduction_brd ("CommandeBonReductionNavigationRefCommande");

CREATE INDEX "IX_t_e_client_clt_CbClientNavigationIdCb" ON t_e_client_clt ("CbClientNavigationIdCb");

CREATE INDEX "IX_t_e_commande_cmd_ClientCommandeNavigationIdClient" ON t_e_commande_cmd ("ClientCommandeNavigationIdClient");

CREATE INDEX "IX_t_e_commande_cmd_PaiementCommandeNavigationIdPaiement" ON t_e_commande_cmd ("PaiementCommandeNavigationIdPaiement");

CREATE INDEX "IX_t_e_etape_etp_HebergementEtapeNavigationIdHebergement" ON t_e_etape_etp ("HebergementEtapeNavigationIdHebergement");

CREATE INDEX "IX_t_e_etape_etp_SejourEtapeNavigationIdSejour" ON t_e_etape_etp ("SejourEtapeNavigationIdSejour");

CREATE INDEX "IX_t_e_hebergement_hbg_HotelHebergementNavigationIdPartenaire" ON t_e_hebergement_hbg ("HotelHebergementNavigationIdPartenaire");

CREATE INDEX "IX_t_e_paiement_pmt_ClientPaiementNavigationIdClient" ON t_e_paiement_pmt ("ClientPaiementNavigationIdClient");

CREATE INDEX "IX_t_e_reponseavis_rav_rav_idavis" ON t_e_reponseavis_rav (rav_idavis);

CREATE INDEX "IX_t_e_sejour_sjr_DestinationSejourNavigationIdDestination" ON t_e_sejour_sjr ("DestinationSejourNavigationIdDestination");

CREATE INDEX "IX_t_e_sejour_sjr_ThemeSejourNavigationIdTheme" ON t_e_sejour_sjr ("ThemeSejourNavigationIdTheme");

CREATE INDEX "IX_t_e_visite_vst_CaveVisiteNavigationIdPartenaire" ON t_e_visite_vst ("CaveVisiteNavigationIdPartenaire");

CREATE INDEX "IX_t_e_visite_vst_TypeVisiteVisiteNavigationIdTypeVisite" ON t_e_visite_vst ("TypeVisiteVisiteNavigationIdTypeVisite");

CREATE INDEX "IX_t_h_cave_cav_PartenaireCaveNavigationIdPartenaire" ON t_h_cave_cav ("PartenaireCaveNavigationIdPartenaire");

CREATE INDEX "IX_t_h_hotel_htl_EtoileHotelHotelNavigationNbEtoileHotel" ON t_h_hotel_htl ("EtoileHotelHotelNavigationNbEtoileHotel");

CREATE INDEX "IX_t_h_hotel_htl_PartenaireHotelNavigationIdPartenaire" ON t_h_hotel_htl ("PartenaireHotelNavigationIdPartenaire");

CREATE INDEX "IX_t_h_societe_sct_TypeActiviteSocieteNavigationIdTypeActivite" ON t_h_societe_sct ("TypeActiviteSocieteNavigationIdTypeActivite");

CREATE INDEX "IX_t_j_effectue_efc_ActiviteEffectueNavigationIdActivite" ON t_j_effectue_efc ("ActiviteEffectueNavigationIdActivite");

CREATE INDEX "IX_t_j_effectue_efc_EtapeEffectueNavigationIdEtape" ON t_j_effectue_efc ("EtapeEffectueNavigationIdEtape");

CREATE INDEX "IX_t_j_faitpartiede_fpd_etp_id" ON t_j_faitpartiede_fpd (etp_id);

CREATE INDEX "IX_t_j_imageavis_ima_AvisImageAvisNavigationIdAvis" ON t_j_imageavis_ima ("AvisImageAvisNavigationIdAvis");

CREATE INDEX "IX_t_j_imageavis_ima_ImageImageAvisNavigationIdImage" ON t_j_imageavis_ima ("ImageImageAvisNavigationIdImage");

CREATE INDEX "IX_t_j_participe_ppt_CatParticipantParticipeNavigationIdCatego~" ON t_j_participe_ppt ("CatParticipantParticipeNavigationIdCategorieParticipant");

CREATE INDEX "IX_t_j_participe_ppt_SejourParticipeNavigationIdSejour" ON t_j_participe_ppt ("SejourParticipeNavigationIdSejour");

CREATE INDEX "IX_t_j_reservation_rsv_CommandeReservationNavigationRefCommande" ON t_j_reservation_rsv ("CommandeReservationNavigationRefCommande");

CREATE INDEX "IX_t_j_reservation_rsv_SejourReservationNavigationIdSejour" ON t_j_reservation_rsv ("SejourReservationNavigationIdSejour");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230309142427_CreationBDVinoDrill', '6.0.14');

COMMIT;